### ISSUE TITLE
Infinite, unstoppable loop if zoom is greater than allowed maximum

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Tyler.jl#15]
See the below MWE:

```julia
using Tyler, MapTiles, TileProviders, GLMakie
provider = TileProviders.NASAGIBS(:ViirsEarthAtNight2012)
m = Tyler.Map(HyperRectangle{2, Float32}(Float32[73.675735, 14.7520275], Float32[0.6598676, 1.0475613]), 15;
    provider, min_tiles=8, max_tiles=16, figure=Figure(resolution=(1000, 600)))
```
this causes a loop that continuously prints out warnings of the form "z greater than max zoom!".  I wasn't able to copy it, but that was the gist.

(also, what exactly is zoom, and how do I find its max/min?)

**Comment by rafaqz** [comment]
Yeah I noticed this too.

Zoom levels are numbers 0 to 23, but the ranges vary with tile provider (read the json in TileProviders.jl) I think each level is 4x magnification.

**Comment by asinghvi17** [comment]
Gotcha, thanks.  Will add that to the docs at some point.

**Comment by asinghvi17** [comment]
It errors now
