### ISSUE TITLE
Use figure resulution to choose zoom level

### ISSUE THREAD

**Issue by rafaqz** [MakieOrg/Tyler.jl#17]
Higher resolution figures should have more tiles, but currently the resolution has no effect and large plots appear a little pixelated.

**Comment by SimonDanisch** [comment]
Ah, I guess we must have removed that... In my initial prototype we did use the resolution!

**Comment by visr** [comment]
MapTiles has this function for determining the resolution which can be used: 
https://github.com/JuliaGeo/MapTiles.jl/blob/a2c818a921bb1737ff54537aace7e4f57fde2194/src/tiles.jl#L10

**Comment by rafaqz** [comment]
It's actually the opposite function we need- getting the z from extent and resolution. I've written a function for that in MapTiles.jl.

@SimonDanisch how do we get the resolution of a figure?

**Comment by lazarusA** [comment]
@rafaqz 
if I do
`fig = lines(1:10)`

 then 

`fig.figure.scene.theme.resolution.val` 

would output the figure's resolution.
