### ISSUE TITLE
Map should accept Extent as rect input

### ISSUE THREAD

**Issue by alex-s-gardner** [MakieOrg/Tyler.jl#20]
It would be nice if Map also accepted a Extents.jl extent as input:

i.e. 
Map(rect::Union{Rect, Extent}, ..... )

**Comment by rafaqz** [comment]
Should be an easy PR, we already use Extent internally

**Comment by alex-s-gardner** [comment]
I see that the first operation of `rect` is to convert to an `Extent` so we only need to add a check on the type of rect... I'll add that in a PR now

**Comment by alex-s-gardner** [comment]
#22
