### ISSUE TITLE
provider CartoDB doesn't work

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/Tyler.jl#28]
The CartoDB() is not working here, but it does when using https://github.com/JuliaGeo/Leaflet.jl, I checked and the call to the url is the same in both cases, namely 

```
Provider("https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png", Dict{Symbol, Any}(:url => "https://{s}.basemaps.cartocdn.com/{variant}/{z}/{x}/{y}{r}.png", :attribution => "(C) OpenStreetMap contributors (C) CARTO", :variant => "light_all", :name => "CartoDB.Positron", :subdomains => "abcd", :html_attribution => "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors &copy; <a href=\"https://carto.com/attributions\">CARTO</a>", :max_zoom => 20))
```

however something goes wrong [here](https://github.com/MakieOrg/Tyler.jl/blob/63b9173cd7c5f8c7fdb0f6a24eac3c8b816db3cc/src/Tyler.jl#L216), at fetching time. I don't seem to find the differences. Help? [Leaflet.jl](https://github.com/JuliaGeo/Leaflet.jl) is doing definitely something different.

**Comment by SimonDanisch** [comment]
maybe its not image based?

**Comment by rafaqz** [comment]
Works fine for me??

**Comment by lazarusA** [comment]
how? MWE

**Comment by rafaqz** [comment]
I just used the readme example

```julia
using Tyler, GLMakie, TileProviders
tyler = Tyler.Map(Rect2f(-0.0921, 51.5, 0.04, 0.025); provider=CartoDB())
```

**Comment by lazarusA** [comment]
Mmmm... do you have something else on your system/env? tokens, keys?

I keep getting:

```
@ Tyler ~/.julia/packages/Tyler/lX5Nf/src/Tyler.jl:243
[ Info: requeing after download error!
┌ Warning: error while downloading tile
│   exception = HTTP.Exceptions.ConnectError("https://.basemaps.cartocdn.com/light_all/8/127/85{r}.png", DNSError: .basemaps.cartocdn.com, unknown node or service (EAI_NONAME))
└ @ Tyler ~/.julia/packages/Tyler/lX5Nf/src/Tyler.jl:243
[ Info: requeing after download error!
┌ Warning: error while downloading tile
│   exception = HTTP.Exceptions.ConnectError("https://.basemaps.cartocdn.com/light_all/14/8188/5448{r}.png", DNSError: .basemaps.cartocdn.com, unknown node or service (EAI_NONAME))
└ @ Tyler ~/.julia/packages/Tyler/lX5Nf/src/Tyler.jl:243
┌ Warning: error while downloading tile
│   exception = HTTP.Exceptions.ConnectError("https://.basemaps.cartocdn.com/light_all/11/1023/681{r}.png", DNSError: .basemaps.cartocdn.com, unknown node or service (EAI_NONAME))
└ @ Tyler ~/.julia/packages/Tyler/lX5Nf/src/Tyler.jl:243
```

**Comment by rafaqz** [comment]
hmm weird, I'm in spain and no error

**Comment by rafaqz** [comment]
I'm on a branch I totally forgot about :sweat_smile: 
https://github.com/JuliaGeo/TileProviders.jl/pull/7/files

**Comment by rafaqz** [comment]
Ok pull TileProviders.jl master.

It seems to have heisenbug in CI I cant reproduce locally, if you have 1.6 lying around could you try running the tests?

**Comment by lazarusA** [comment]
>Ok pull TileProviders.jl master.
yes, that solves the issue. Maybe tag a new release. Thanks. And sorry, no Julia 1.6, so not tests.

**Comment by rafaqz** [comment]
I probably cant tag a release with those failing tests? Not sure what to do about it
