### ISSUE TITLE
Could Tyler support scrollable and zoomable animated maps?

### ISSUE THREAD

**Issue by alex-s-gardner** [MakieOrg/Tyler.jl#31]
Thinking about how the Julia Geo ecosystem could wow other communities, I was wondering if it could be possible to create interactive (scrollable and zoomable) animated maps. For example is there a way to make the "Whale shark example trajectory" interactive?

**Comment by lazarusA** [comment]
the "Whale shark example trajectory" is interactive!

**Comment by alex-s-gardner** [comment]
No... surely not... isn't it saving frame by frame... I'll go check it out

**Comment by lazarusA** [comment]
fair enough, you'll need to comment out that part. But that's all that is needed.

**Comment by alex-s-gardner** [comment]
Damn... I'll need to make a post for this... this is a super cool feature that would not trivial to with your own data in something like leaflet.

**Comment by rafaqz** [comment]
You can also use Tyler with a DynamicGrids.jl simulation over the top, with input from MakieDraw.jl controling it!

All interactive and zoomable and fast. There is going to be so many bling animations...

**Comment by alex-s-gardner** [comment]
@rafaqz do you have an example that uses DynamicGrids.jl and MakieDraw.jl ?

**Comment by rafaqz** [comment]
Not with Tyler, just GLMakie (see the MakieDraw readme) but it works just the same with Tyler.

I'll make one soon hopefully.
