### ISSUE TITLE
Fill frame withzoom (i.e. keep image apect ratio of image fixed)

### ISSUE THREAD

**Issue by alex-s-gardner** [MakieOrg/Tyler.jl#37]
When an extent is defined to zoom into the aspect ratio of the displayed image changes. I think this should be changed such that the zoomed image always fills the frame. Otherwise the area of display keeps changing and looks hacky.

**Comment by rafaqz** [comment]
Should be easy to fix, have a go.

**Comment by alex-s-gardner** [comment]
Looking through the code I can't seem to find where a zoom rectangle triggers a response.

**Comment by rafaqz** [comment]
https://github.com/MakieOrg/Tyler.jl/blob/346b2c78234374c7493c94c229804570fe65844f/src/Tyler.jl#L138-L142
