### ISSUE TITLE
ImageMagick_jll dependancies causing issues

### ISSUE THREAD

**Issue by alex-s-gardner** [MakieOrg/Tyler.jl#58]
I updated packages and Tyler.jl broke due to this issue: https://github.com/JuliaIO/ImageMagick.jl/issues/209

To fix the issue I had to explicitly add:
```
add ImageMagick_jll@6.9.12
```

removing `ImageMagick` dependency in the future in favor of `ImageIO` would probably be a good idea as it looks like there are plans to deprecate  ImageMagick_jll

**Comment by felixcremer** [comment]
Maybe a stopgap solution until we switch to ImageIO would be to add ImageMagick_jll as an explicit dependency and to add a compat entry to exclude non working versions.
