### ISSUE TITLE
Tyler is plotting the wrong tiles with Makie 0.21

### ISSUE THREAD

**Issue by felixcremer** [MakieOrg/Tyler.jl#82]
With Makie 0.21 on this branch https://github.com/MakieOrg/Makie.jl/tree/breaking-0.21 Tyler is somehow randomly  plotting the wrong tiles see the appearance of France in two zoom levels in the image below.

This is the code I used to produce the plot:

```julia

using Tyler, GLMakie
using Extents

fig = Figure()

nax = Axis(fig[1,1])
london = Rect2f(-0.0921, 51.5, 0.04, 0.025)
m = Tyler.Map(london, figure=fig, axis=nax)
```

This problem does not appear with Makie 0.20.

![image](https://github.com/MakieOrg/Tyler.jl/assets/17124431/7be4612f-c0c6-47c4-bc13-9d60ee6d71de)

**Comment by asinghvi17** [comment]
I can replicate this locally, and the error seems to happen regardless of which zoom level I'm on.  Scaling the z levels also doesn't solve this.  It looks almost as if there are stale tiles that become ill-positioned?

**Comment by asinghvi17** [comment]
This is still an issue on the latest Makie master, although it seems to only happen at higher zoom levels.  When zooming in I stop seeing this.

**Comment by SimonDanisch** [comment]
We'll need an MWE to properly debug this....

**Comment by asinghvi17** [comment]
It looks almost as if there's something wrong with the way `tile.y` is translated into a y coordinate maybe?

**Comment by felixcremer** [comment]
> Hm weird... I would have suspected z-fighting, but the z should be quite far appart

Isn't this only moving all z levels? Should we muliply the z level by a factor?

**Comment by asinghvi17** [comment]
I think there was a scaling that multiplied all z values by 0, that was one issue I fixed in my PR I think.
