### ISSUE TITLE
Advanced Provider with heavy dependencies

### ISSUE THREAD

**Issue by SimonDanisch** [MakieOrg/Tyler.jl#94]
I'm currently adding Elevation + Pointcloud providers and was about to put them in a new Package since they have quite some juicy dependencies.
Do we care about this, or do we rather have everything in one place here and have Tyler be more heavyweight in turn?
I dont see how we could use pkg extensions for this, so don't think this is an option.

**Comment by asinghvi17** [comment]
How heavyweight are we talking here?  I think Tyler should work on every platform Makie works on, since it is pretty much pure Julia save for the image libraries (and openGL/cairo).  If that line isn't crossed then it shouldn't be too much of an issue to add dependencies...

**Comment by lazarusA** [comment]
I think Tyler should eventually bring together as many features as possible. So, seeing it grow on dependencies should be expected.

**Comment by rafaqz** [comment]
Sounds fine to me. 

Should we make ElevationProviders.jl and PointCloudProviders.jl to wrap the provider lists?

**Comment by asinghvi17** [comment]
> Should we make ElevationProviders.jl and PointCloudProviders.jl to wrap the provider lists?

Not sure, they could probably live as extensions on MapTiles.jl and then Tyler just depends on the activation packages for those.
